### ISSUE TITLE
metrics for dead pods persist

### ISSUE THREAD

**Issue by theRealWardo** [muxinc/certificate-expiry-monitor#7]
steps to reproduce:

1. delete a pod that is being monitored.
1. all of the metrics exposed by the certificate expiry monitor with that pod's labels remain.

current work around:

- restart the certificate expiry monitor

proposed resolution:

1. keep a list of all the pods we have ever monitored.
1. when updating the list, diff the new value with the old one in order to identify pods that have gone away.
1. delete all metrics for those pods using the prometheus `Delete(labels Labels)` function

**Comment by jacobrandall** [comment]
Wait, the prometheus `Delete(labels Labels)` would delete all the history for that as well right?

**Comment by theRealWardo** [comment]
no. that isn't how the prometheus client instrumentation API works. it simply deletes the exported metric on the `/metrics` endpoint.

**Comment by com6056** [comment]
fixed in https://github.com/muxinc/certificate-expiry-monitor/pull/11
